---
swagger: '2.0'
info:
  version: v1
  title: ''
  description: "# Getting Started
  
  ## Security
  
  ### HTTPS

  All api calls and callbacks require HTTPS. Your service will need a valid SSL certificate and be accesible via the standard SSL port (port 443).

  ## Making an api request

  PUT https://uk-partnerapi.just-eat.io/orders/abcd1234 HTTP/1.1<br/>
  Host: uk-partnerapi.just-eat.io/<br/>
  Content-Length: 1000<br/>
  Content-Type: application/json<br/>
  Authorization: JE-API-KEY abcd123456789
  "
host: partnerapiurl
schemes:
- https
securityDefinitions:
  API Key:
    type: apiKey
    name: Authorization
    in: header
    description: "<p>All api calls require an Authorization
    Key which will be provided by JUST EAT.<p><p>The key needs to be provided in the
    header as follows: </p><p><b>Authorization: JE-API-KEY {Your-Key-Here}</b></p>. The key is
    case sensitive."
security:
  - API Key: []
consumes:
  - application/json
produces:
- application/json
tags:
  - name: restaurant-api
    x-displayName: Restaurant Webhooks
  - name: restaurant-api
    x-displayName: Restaurant API
  - name: order-delivery-webhooks
    x-displayName: Order Delivery Webhooks
  - name: order-acceptance-api
    x-displayName: Order Acceptance API
  - name: order-api
    x-displayName: Order API
  - name: order-webhooks
    x-displayName: Order Webhooks
  - name: order-delivery-api
    x-displayName: Order Delivery API
  - name: delivery-pools-api
    x-displayName: Delivery Pools API
x-tagGroups:
  - name: Delivery Pools
    tags:
      - delivery-pools-api
  - name: Order Acceptance
    tags: 
      - order-acceptance-api
  - name: Orders
    tags: 
      - order-api
      - order-webhooks
  - name: Order Delivery
    tags:
      - order-delivery-webhooks
      - order-delivery-api
  - name: Restaurants
    tags:
      - restaurant-api
      - restaurant-webhooks